defaultRules:
  create: true
  disabled:
    Watchdog: true
    InfoInhibitor: true

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.kubernetes.docker.internal
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-query-frontend.monitoring:3100

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.kubernetes.docker.internal
    paths:
      - /
    externalUrl: ""
    retention: 10d
    retentionSize: "8GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

