defaultRules:
  create: true
  disabled:
    Watchdog: true
    InfoInhibitor: true

alertmanager:
  ingress:
    enabled: true
    hosts: 
      - alertmanager.kubernetes.docker.internal
    paths:
     - /
  config:
    global:
      resolve_timeout: 5m
      # The API URL to use for Slack notifications.
      #slack_api_url: <secret>
      #slack_api_url_file: <filepath>
  receivers:
    - name: default-receiver
      # slack_configs:
      #  - channel: '@you'
      #    send_resolved: true
      telegram_config:
      - bot_token: "6531841395:AAFZcJA67hvcG6uWPfxW76Y1R41nz8wskwI"
        chat_id: "@PromTest2123"
        send_resolved: true
        parse_mode: HTML

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.kubernetes.docker.internal

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.kubernetes.docker.internal
    paths:
      - /
    externalUrl: ""
    retention: 10d
    retentionSize: "8GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

