alertmanager:
  ingress:
    enabled: true
    hosts: 
      - alertmanager.kubernetes.docker.internal
    paths:
     - /

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.kubernetes.docker.internal

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.kubernetes.docker.internal
    paths:
      - /
    externalUrl: ""
    retention: 10d
    retentionSize: "8GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi