# Default values for metrics-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.k8s.io/metrics-server/metrics-server
  #tag: "latest"
  pullPolicy: IfNotPresent

replicas: 3

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

podDisruptionBudget:
  enabled: true
  minAvailable: 1

metrics:
  enabled: true

serviceMonitor:
  enabled: true
  interval: 1m
  scrapeTimeout: 10s