apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
    app.kubernetes.io/component: blackbox
spec:
  containers:
    - name: nginx2
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    name: nginx2
    app.kubernetes.io/component: blackbox
spec:
  ports:
    - port: 80
  selector:
    app: nginx2
  type: ClusterIP