apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: nginx3
    app.kubernetes.io/component: blackbox
spec:
  containers:
    - name: nginx3
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx3
  labels:
    name: nginx3
    app.kubernetes.io/component: blackbox
spec:
  ports:
    - port: 80
  selector:
    app: nginx3
  type: ClusterIP