k delete customresourcedefinitions.apiextensions.k8s.io applications.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io applicationsets.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io appprojects.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io clusterworkflowtemplates.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io cronworkflows.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io workflowartifactgctasks.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io workfloweventbindings.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io workflows.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io workflowtaskresults.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io workflowtasksets.argoproj.io  
k delete customresourcedefinitions.apiextensions.k8s.io workflowtemplates.argoproj.io  