redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
  
repoServer:
  replicas: 2

applicationSet:
  replicas: 2

global:
  domain: argocd.kubernetes.docker.internal

certificate:
  enabled: true

configs:
  params:
    server.insecure: true
