apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: kube-prometheus-stack 
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    receiver: "email-test"
    groupBy: ['instance', 'alertname']
    groupWait: 45s
    groupInterval: 10m
    repeatInterval: 1h
    routes:

  receivers:
    - name: 'null'
    - name: 'telegram-test'
      telegramConfigs:
        - botToken:
            name: telegram-test-config
            key: apiToken
          chatID: -1002019095946
          message: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
          sendResolved: true
    - name: 'email-test'
      emailConfigs:
        - to: notify@example.com
          from: noreply@example.com
          requireTLS: false
          smarthost: email-mailhog.email.svc.cluster.local:1025
          sendResolved: true