apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pick
  region: us-east-2
  version: "1.31"

iam:
  withOIDC: true

nodeGroups:
  - name: default-nodegroup
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true

addons:
- name: vpc-cni 
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest 
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  wellKnownPolicies:      
    ebsCSIController: true