image:
  #registry: cgr.dev
  #repository: chainguard/redis-server-bitnami
  #tag: latest
  #digest: "sha256:b2c8322f1785cf2e4ce805959faffe84b505ef7572e84cb27ca43fc680f74fad"
  pullPolicy: IfNotPresent

auth:
  enabled: false

commonConfiguration: |-
  appendonly yes
  maxmemory 200mb
  maxmemory-policy allkeys-lru
  save ""

master:
  disableCommands: []
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 0.5
      memory: 128Mi
  persistence:
    size: 500Mi

replica:
  replicaCount: 3
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 0.5
      memory: 128Mi
  persistence:
    size: 500Mi

pdb:
  create: true
  minAvailable: 1

metrics:
  enabled: false
  image:
    registry: cgr.dev
    repository: chainguard/prometheus-redis-exporter
    digest: "sha256:53d74b9b90beed6bbba6c910703e7db1e90494f86396861e9f860c4cb4b58709"
    pullPolicy: Always
  serviceMonitor:
    enabled: false