commonConfiguration: |-
  appendonly yes
  maxmemory 500mb
  maxmemory-policy allkeys-lru
  save ""

master:
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 0.5
      memory: 128Mi
  persistence:
    size: 1Gi

replica:
  replicaCount: 5
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 0.5
      memory: 128Mi
  persistence:
    size: 1Gi

metrics:
  prometheusRule:
    rules:
      - alert: RedisDown
        expr: redis_up{service="{{ template "common.names.fullname" . }}-metrics"} == 0
        for: 2m
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance {{ "{{ $labels.instance }}" }} down
          description: Redis&reg; instance {{ "{{ $labels.instance }}" }} is down
      - alert: RedisMemoryHigh
        expr: >
          redis_memory_used_bytes{service="{{ template "common.names.fullname" . }}-metrics"} * 100
          /
          redis_memory_max_bytes{service="{{ template "common.names.fullname" . }}-metrics"}
          > 90
        for: 2m
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance {{ "{{ $labels.instance }}" }} is using too much memory
          description: |
            Redis&reg; instance {{ "{{ $labels.instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.
      - alert: RedisKeyEviction
        expr: |
          increase(redis_evicted_keys_total{service="{{ template "common.names.fullname" . }}-metrics"}[5m]) > 0
        for: 1s
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance {{ "{{ $labels.instance }}" }} has evicted keys
          description: |
            Redis&reg; instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.