master:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 0.5
      memory: 128Mi
  persistence:
    size: 1Gi

replica:
  replicaCount: 2
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 0.5
      memory: 128Mi
  persistence:
    size: 1Gi