name: Build and Push Giropops Senhas

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  GIROPOPS_SENHAS_TAG: ${{ github.sha }}

jobs:
  lint-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Check commit messages
        uses: ahmadnassri/action-commit-lint@v2
        with:
          config: angular

  lint-docker-file:
    name: Lint Docker File
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Scan dockerfile com Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: giropops-senhas/Dockerfile
          config: configs/hadolint/hadolint-config.yaml

  lint-kubernetes-manifests:
    name: Lint Kubernetes Manifests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - uses: imranismail/setup-kustomize@v2
      
      - name: Gerando os manifests para lint
        run: |
          kustomize build giropops-senhas/manifests/overlays/eks >> ./giropops-senhas/manifests/rendered-manifests.yaml

      - name: Scan yaml files com kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: ./giropops-senhas/manifests/rendered-manifests.yaml
          config: configs/kubelinter/kubelinter-config.yaml
          format: sarif
          output-file: kube-linter.sarif
  
  sast:
    name: SAST
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: SAST
        run: |
          semgrep giropops-senhas/src \
            --sarif --output sast.sarif \
            --metrics=off \
            --config="p/default"

      - name: Upload dos resultados pra security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'sast.sarif'

    needs: [
      lint-commit-message,
      lint-docker-file,
      lint-kubernetes-manifests
    ]

  docker:
    name: Build
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Buidando a imagem do Dockerfile
        run: |
          make build-image

      - name: Verificando vulnerabilidades com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/giropops-senhas-python-chainguard:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload dos resultados pra security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Sign and Push
        run: |
          make push-image-dockerhub-ci

    needs: [sast]

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurando credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Instalando kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy do Giropops Senhas no EKS
        run: |
          make deploy-giropops-senhas-aws

    needs: [docker]